### ISSUE TITLE
package installation failed

### ISSUE THREAD

**Issue by D-Husband** [adeverse/adespatial#26]
Anyone have a solution?

ERROR: package installation failed
Error: Failed to install 'adespatial' from GitHub:
  System command 'Rcmd.exe' failed, exit status: 1, stdout & stderr were printed
In addition: There were 28 warnings (use warnings() to see them)

**Comment by aursiber** [comment]
Hi,
Which command line generates this error?
Can you please tell me the result of `sessionInfo()`?
But it seems to me that the problem is not with `adespatial` but rather with your installation of R.
