### ISSUE TITLE
Error running msr.4thcorner

### ISSUE THREAD

**Issue by diogoprov** [adeverse/adespatial#3]
Dear @sdray ,
I'm trying to run the example of the new function msr.4thcorner, but I keep getting this error:

```
Error in hist.default(vec.sim, plot = FALSE, nclass = 10) : character(0)
In addition: Warning messages:
1: In max(vec.sim) : no non-missing arguments to max; returning -Inf
2: In min(vec.sim) : no non-missing arguments to min; returning Inf
3: In min(x) : no non-missing arguments to min; returning Inf
4: In max(x) : no non-missing arguments to max; returning -Inf
```

I'm using 

```
> R.Version()$version.string; R.Version()$platform
[1] "R version 3.4.0 (2017-04-21)"
[1] "x86_64-apple-darwin15.6.0"
```
and installed from github 
```
> packageVersion("adespatial")
[1] ‘0.0.8’
```

I also tried to run it with my own data, but I get the exact same error. Que pensez vous?

Merci boucoup!

**Comment by sdray** [comment]
Hi,

sorry, I did not update requirements in DESCRIPTION file. You should install the last version of ade4 (1.7-7). It is available on github and just submitted to CRAN (so available in few days)

Cheers
.

**Comment by diogoprov** [comment]
Thanks a lot @sdray !
