### ISSUE TITLE
Clarification of "global" MEM selection method

### ISSUE THREAD

**Issue by JosiahParry** [adeverse/adespatial#32]
I've been reading through the adespatial docs and the cited literature (Dray 2006, and the 3 Bauman 2018 papers) and I continue to struggle identifying what the "global" MEM selection method is doing. 

In  Bauman 2018 "Optimizing the choice of a spatial weighting matrix in eigenvector-based methods" writes 

> ...  our method consists in (1) performing a global test (based on the R2 of the model considering all MEM variables as explanatory variables) 

This makes it sounds like the Global test method is only possible in a univariate case. It does so by calculating `lm(y ~ all_mems)`.

In Bauman et al  2018 "Disentangling good from bad practices in the selection of spatial or phylogenetic
eigenvectors" the first approach is referred to as the "AIC approach." Is this the same as the "global"? It does this by sorting MEMs based on their R2 (which, again, sounds only possible in the univariate case). Then, MEMs are added in a stepwise manner to a regression. Then the subset of mems that minimizes AICc is returned. 

However, this figure

<img width="541" alt="image" src="https://github.com/adeverse/adespatial/assets/13534508/f816d52f-a000-4576-b469-b02d32c1ea17">

when coupled with the source code's `.testGlobal` https://github.com/adeverse/adespatial/blob/c0cfcf499d8ba54148d9b5171b6ea74970fc83e0/R/mem.select.R#L390 make it seem that this is a _different_ R2 measure than the one derived from a linear regression. 

This function performs "Redundancy Analysis" from {vegan}. Looking into this is a bit hard as the only source cited is from Legendre & Legendre p. 650 which is a textbook that can not readily be viewed. But based on Legendre & Anderson 1999—which contains math notation beyond my comprehension—RDA is a type of ANOVA that derives dummy variables from PCoA. 

All that to say, it is unclear as to what the global method is actually doing under the hood. Further, all my reading suggests that it can only be used in a univariate case. However adespatial supports multivariate data with the global method. 

Can you clarify how this method works? Perhaps there is a paper I've missed that spells it out clearly.

**Comment by sdray** [comment]
Hi,

R2 can be computed for univariate y (as you suggest) but also for multivariate response.  You can have a look to Peres-Neto et al, Ecology,  2006 (available [here](https://www.numericalecology.com/Reprints/Peres-Neto_et_al_2006_with_app.pdf)) for more details.

Cheers
